### ISSUE TITLE
Call to undefined method [package]

### ISSUE THREAD

**Issue by loranger** [PhiloNL/Laravel-5-Facebook#3]
Hello,

In now try this package with the stable L5 version and it seems the ServiceProvider did change, I cannot use Laravel-5-Facebook, one installed and declared in my app.php, I got an Exception rised :

```shell
$ art tail
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in project/storage/framework/compiled.php:4346
```

How can I make it work again ?
Thanks

**Comment by markioooo** [comment]
I have the same issue.

**Comment by PhiloNL** [comment]
Should be fixed now.

**Comment by markioooo** [comment]
Great! I'll try it out.
