### ISSUE TITLE
Getting 'facebook access token' from 'app/config/services.php'

### ISSUE THREAD

**Issue by GarySwift** [PhiloNL/Laravel-5-Facebook#4]
When you say  `<facebook access token>`, I presume you mean the `client_id` and `client_secret` that was set as follows in `app/config/services.php`.
```php
    'facebook' => [
        'client_id' => '1234567891234612',
        'client_secret' => 'a837f07gjsoxya721964120z7dkgr',
    ],
```
But how do I request the object from `app/config/services.php` and use it in a controller?

**Comment by PhiloNL** [comment]
Hi @GarySwift 
No, you need to enter the access token you get from Facebook:
https://developers.facebook.com/docs/facebook-login/access-tokens

**Comment by GarySwift** [comment]
Hi @PhiloNL. Yes, I had created an app on Facebook and used my own id and secret in services.php.

**Comment by PhiloNL** [comment]
@GarySwift Access token is something different. Please see the Facebook docs.

**Comment by GarySwift** [comment]
@PhiloNL. OK, will do, thanks for the help.
